# Generated by Django 5.0.6 on 2024-06-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_description_publisher_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='wishlist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
