# Generated by Django 5.0.6 on 2024-07-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_member_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='wishlist',
        ),
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
