# Generated by Django 5.0.6 on 2024-07-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
